// <auto-generated />
using System;
using GtKanu.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GtKanu.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260111152753_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Boat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRentalDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("boats", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.BoatRental", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BoatId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoatId");

                    b.HasIndex("UserId");

                    b.ToTable("boat_rentals", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.ClubhouseBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("clubhouse_bookings", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.EmailQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorrelationId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextSchedule")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Sent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("NextSchedule", "Sent", "IsPrio", "Created");

                    b.ToTable("email_queue", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FoodListId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoodListId");

                    b.ToTable("foods", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.FoodBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FoodId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvoiceId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("UserId", "BookedOn");

                    b.ToTable("food_bookings", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.FoodInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvoicePeriodId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoicePeriodId");

                    b.HasIndex("UserId");

                    b.ToTable("food_invoices", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.FoodInvoicePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("From")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("To");

                    b.ToTable("food_invoice_periods", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.FoodList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ValidFrom");

                    b.ToTable("food_lists", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityRoleClaimGuid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_role_claims", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityRoleGuid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("identity_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fbbcf7bf-8cbf-440f-939c-f67631109aa0"),
                            ConcurrencyStamp = "CFAD6F62-EEAA-4ECD-B847-0762C704EC45",
                            Name = "administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("1fb64576-3f90-4ce9-8c3a-cfa13f587167"),
                            ConcurrencyStamp = "6EE38FDC-5CE5-42FD-A5A5-168573DB2F86",
                            Name = "treasurer",
                            NormalizedName = "TREASURER"
                        },
                        new
                        {
                            Id = new Guid("1d4d07e0-40ae-45cb-a4f6-397672f3605b"),
                            ConcurrencyStamp = "995137CB-BD7B-4747-884E-A7467F3C0A3A",
                            Name = "kitchen",
                            NormalizedName = "KITCHEN"
                        },
                        new
                        {
                            Id = new Guid("03a90da5-abf0-45e9-9b80-cdac790b7105"),
                            ConcurrencyStamp = "956824FE-2F13-4919-B2D2-0E60BECFCA12",
                            Name = "member",
                            NormalizedName = "MEMBER"
                        },
                        new
                        {
                            Id = new Guid("9dc6f0a7-7116-4820-8b76-4f20b73053ee"),
                            ConcurrencyStamp = "3096E774-529C-41B4-8CD3-355E0D2C930D",
                            Name = "interested",
                            NormalizedName = "INTERESTED"
                        },
                        new
                        {
                            Id = new Guid("2ddc9bec-eb96-4cd5-94b4-dd0d99a19664"),
                            ConcurrencyStamp = "F3BFC39C-70B7-4E91-A70B-131925290446",
                            Name = "tripmanager",
                            NormalizedName = "TRIPMANAGER"
                        },
                        new
                        {
                            Id = new Guid("8772da16-fbbc-46af-a52c-c83c90ca74c9"),
                            ConcurrencyStamp = "49DD2CBF-AAC9-4015-9016-9E3ED25547DF",
                            Name = "chairperson",
                            NormalizedName = "CHAIRPERSON"
                        },
                        new
                        {
                            Id = new Guid("ef80d842-4a0f-4613-82eb-48a670bac21d"),
                            ConcurrencyStamp = "EA00C945-985C-42AD-B149-7D6FBCE9C279",
                            Name = "usermanager",
                            NormalizedName = "USERMANAGER"
                        },
                        new
                        {
                            Id = new Guid("f9493060-30b8-4bf3-a4be-74630b0fa423"),
                            ConcurrencyStamp = "D8FEF733-1C63-433F-916F-99B8645D1487",
                            Name = "fleetmanager",
                            NormalizedName = "FLEETMANAGER"
                        },
                        new
                        {
                            Id = new Guid("668ef80a-9f57-4961-beac-540ad8003241"),
                            ConcurrencyStamp = "4B04648D-DE82-4B0B-B014-3CE0BE5454FD",
                            Name = "boatmanager",
                            NormalizedName = "BOATMANAGER"
                        },
                        new
                        {
                            Id = new Guid("afd40e75-dcfe-4c46-9d4c-ff701f225179"),
                            ConcurrencyStamp = "4B04648D-DE82-4B0B-B014-3CE0BE5454FD",
                            Name = "housemanager",
                            NormalizedName = "HOUSEMANAGER"
                        },
                        new
                        {
                            Id = new Guid("6dc9442b-3279-46cc-95c0-1d4f8c3d31f0"),
                            ConcurrencyStamp = "4B04648D-DE82-4B0B-B014-3CE0BE5454FD",
                            Name = "mailingmanager",
                            NormalizedName = "MAILINGMANAGER"
                        },
                        new
                        {
                            Id = new Guid("02c2dfe3-7331-45f6-929b-f983273f2d74"),
                            ConcurrencyStamp = "4B04648D-DE82-4B0B-B014-3CE0BE5454FD",
                            Name = "wikimanager",
                            NormalizedName = "WIKIMANAGER"
                        });
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityUserClaimGuid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_claims", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressNumber")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthenticatorKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorNumber")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeftOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mailings")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("identity_users", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityUserLoginGuid", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_logins", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityUserRoleGuid", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_user_roles", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityUserTokenGuid", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("identity_user_tokens", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Mailing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanSendToAllMembers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmailCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsYoungPeople")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherRecipients")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("mailings", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.MyMailing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasRead")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MailingId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MailingId");

                    b.HasIndex("UserId");

                    b.ToTable("my_mailings", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("Categories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxBookings")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Start", "End");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.TripBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfirmedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TripId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("trip_bookings", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.TripChat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TripId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("trip_chats", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Tryout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBookings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Anfängertraining");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tryouts", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.TryoutBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfirmedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TryoutId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TryoutId");

                    b.HasIndex("UserId");

                    b.ToTable("tryout_bookings", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.TryoutChat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TryoutId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TryoutId");

                    b.HasIndex("UserId");

                    b.ToTable("tryout_chats", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInUse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.VehicleBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfirmedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VehicleId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("vehicle_bookings", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.WikiArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("wiki_articles", (string)null);
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.BoatRental", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.Boat", "Boat")
                        .WithMany("BoatRentals")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("BoatRentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Boat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Food", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.FoodList", "FoodList")
                        .WithMany("Foods")
                        .HasForeignKey("FoodListId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FoodList");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.FoodBooking", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.Food", "Food")
                        .WithMany("Bookings")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GtKanu.Infrastructure.Database.Entities.FoodInvoice", "Invoice")
                        .WithMany("Bookings")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("FoodBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Food");

                    b.Navigation("Invoice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.FoodInvoice", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.FoodInvoicePeriod", "InvoicePeriod")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoicePeriodId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("FoodInvoices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("InvoicePeriod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityRoleClaimGuid", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityRoleGuid", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityUserClaimGuid", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityUserLoginGuid", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityUserRoleGuid", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityRoleGuid", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityUserTokenGuid", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.MyMailing", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.Mailing", "Mailing")
                        .WithMany("MyMailings")
                        .HasForeignKey("MailingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("MyMailings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Mailing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Trip", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.TripBooking", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.Trip", "Trip")
                        .WithMany("TripBookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("TripBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.TripChat", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.Trip", "Trip")
                        .WithMany("TripChats")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("TripChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Tryout", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("Tryouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.TryoutBooking", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.Tryout", "Tryout")
                        .WithMany("TryoutBookings")
                        .HasForeignKey("TryoutId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("TryoutBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Tryout");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.TryoutChat", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.Tryout", "Tryout")
                        .WithMany("TryoutChats")
                        .HasForeignKey("TryoutId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("TryoutChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Tryout");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.VehicleBooking", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("VehicleBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GtKanu.Infrastructure.Database.Entities.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.WikiArticle", b =>
                {
                    b.HasOne("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", "User")
                        .WithMany("WikiArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Boat", b =>
                {
                    b.Navigation("BoatRentals");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Food", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.FoodInvoice", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.FoodInvoicePeriod", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.FoodList", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityRoleGuid", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.IdentityUserGuid", b =>
                {
                    b.Navigation("BoatRentals");

                    b.Navigation("FoodBookings");

                    b.Navigation("FoodInvoices");

                    b.Navigation("MyMailings");

                    b.Navigation("TripBookings");

                    b.Navigation("TripChats");

                    b.Navigation("Trips");

                    b.Navigation("TryoutBookings");

                    b.Navigation("TryoutChats");

                    b.Navigation("Tryouts");

                    b.Navigation("UserRoles");

                    b.Navigation("VehicleBookings");

                    b.Navigation("WikiArticles");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Mailing", b =>
                {
                    b.Navigation("MyMailings");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Trip", b =>
                {
                    b.Navigation("TripBookings");

                    b.Navigation("TripChats");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Tryout", b =>
                {
                    b.Navigation("TryoutBookings");

                    b.Navigation("TryoutChats");
                });

            modelBuilder.Entity("GtKanu.Infrastructure.Database.Entities.Vehicle", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
